apiVersion: apps/v1
kind: Deployment
metadata:
  name: sentinelai
spec:
  replicas: 3
  template:
    spec:
      containers:
        - name: sentinelai
          imagePullPolicy: IfNotPresent  
          resources:
            requests:
              memory: "256Mi"
              cpu: "200m"
            limits:
              memory: "512Mi"
              cpu: "400m"
          livenessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 15
            periodSeconds: 20
          readinessProbe:
            httpGet:
              path: /status
              port: 8000
            initialDelaySeconds: 15
            periodSeconds: 20
