apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: sentinelai-netpol
spec:
  podSelector:
    matchLabels:
      app: sentinelai
  policyTypes:
    - Ingress
    - Egress
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: sentinelai-dev
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: monitoring
      ports:
        - protocol: TCP
          port: 8000
  egress:
    - to:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: monitoring
      ports:
        - protocol: TCP
          port: 9090
    - ports:
        - protocol: UDP
          port: 53
